// Scandalous — Profile Database v1.0
// Edit this file to add, remove, or update profiles.
// scandal-game.html loads this automatically via <script src="scandal-db.js">.

const SCANDAL_DB = {
  version: '1.0',
  lastUpdated: '2026-03-04',

  daddies: [
    { name:'Pak Rudi',    age:48, city:'Jakarta Selatan', emoji:'🧔',  avatarBg:'linear-gradient(135deg,#1a2a4a,#2a4a6a)',
      budget:50000000, housing:'apartment',   car:'mewah',    vacation:20000000,
      bio:'Pengusaha properti, suka nonton bola dan makan sate bersama.' },
    { name:'Pak Hendra',  age:52, city:'Surabaya',        emoji:'👨‍💼', avatarBg:'linear-gradient(135deg,#2a1a0a,#4a3a1a)',
      budget:30000000, housing:'apartment',   car:'menengah', vacation:10000000,
      bio:'Direktur logistik, hobi golf dan travel Asia setiap tahun.' },
    { name:'Om Dedi',     age:45, city:'Bandung',         emoji:'🕵️', avatarBg:'linear-gradient(135deg,#1a0a2a,#3a1a5a)',
      budget:20000000, housing:'kost',        car:'ekonomi',  vacation:0,
      bio:'Konsultan IT freelance, senang hiking dan kopi specialty.' },
    { name:'Pak Surya',   age:55, city:'Bali',            emoji:'🌴', avatarBg:'linear-gradient(135deg,#0a2a1a,#1a5a3a)',
      budget:100000000, housing:'prime_house', car:'supercar', vacation:50000000,
      bio:'Investor forex, punya villa di Seminyak dan yacht pribadi.' },
    { name:'Pak Anton',   age:49, city:'Jakarta Barat',   emoji:'💼', avatarBg:'linear-gradient(135deg,#1a1a0a,#3a3a1a)',
      budget:40000000, housing:'apartment',   car:'mewah',    vacation:20000000,
      bio:'COO perusahaan retail nasional, suka wine dan jazz malam.' },
    { name:'Mas Bayu',    age:38, city:'Yogyakarta',      emoji:'🎸', avatarBg:'linear-gradient(135deg,#2a0a1a,#4a1a2a)',
      budget:15000000, housing:'kost',        car:'ekonomi',  vacation:0,
      bio:'Musisi dan content creator, traveling keliling Indonesia.' },
    { name:'Pak Wahyu',   age:51, city:'Medan',           emoji:'🏗️', avatarBg:'linear-gradient(135deg,#1a0a0a,#4a1a1a)',
      budget:75000000, housing:'prime_house', car:'supercar', vacation:30000000,
      bio:'Developer perumahan, koleksi jam tangan luxury dan mobil klasik.' },
    { name:'Bang Ferry',  age:43, city:'Makassar',        emoji:'⚓', avatarBg:'linear-gradient(135deg,#0a1a2a,#1a3a4a)',
      budget:25000000, housing:'apartment',   car:'menengah', vacation:10000000,
      bio:'Pengusaha ekspor ikan, hobi memancing dan scuba diving.' },
    { name:'Pak Eko',     age:47, city:'Semarang',        emoji:'🏭', avatarBg:'linear-gradient(135deg,#1a1a1a,#3a3a3a)',
      budget:35000000, housing:'apartment',   car:'menengah', vacation:10000000,
      bio:'Direktur pabrik tekstil, rutin badminton dan senang memasak.' },
    { name:'Bro Kevin',   age:36, city:'Jakarta Utara',   emoji:'🌟', avatarBg:'linear-gradient(135deg,#0a0a2a,#1a1a5a)',
      budget:60000000, housing:'prime_house', car:'mewah',    vacation:30000000,
      bio:'Startup founder yang sudah IPO, digital nomad part-time.' },
    { name:'Pak Slamet',  age:58, city:'Solo',            emoji:'🎋', avatarBg:'linear-gradient(135deg,#1a2a0a,#3a4a1a)',
      budget:10000000, housing:'kost',        car:'ekonomi',  vacation:0,
      bio:'Pensiunan PNS, gemar berkebun dan membaca buku sejarah.' },
    { name:'Mas Rizky',   age:40, city:'Tangerang',       emoji:'✈️', avatarBg:'linear-gradient(135deg,#0a1a1a,#1a4a4a)',
      budget:45000000, housing:'apartment',   car:'mewah',    vacation:20000000,
      bio:'Pilot maskapai nasional, hobi photography dan aviation.' },
    { name:'Pak Bimo',    age:53, city:'Palembang',       emoji:'🛢️', avatarBg:'linear-gradient(135deg,#2a1a0a,#5a3a0a)',
      budget:80000000, housing:'prime_house', car:'supercar', vacation:50000000,
      bio:'Eksekutif perusahaan minyak, golf setiap akhir pekan di resort.' },
    { name:'Mas Ariel',   age:35, city:'Jakarta Pusat',   emoji:'🎬', avatarBg:'linear-gradient(135deg,#0a0a1a,#2a1a4a)',
      budget:55000000, housing:'apartment',   car:'mewah',    vacation:30000000,
      bio:'Sutradara iklan dan film pendek, hidup nomaden antara Jakarta dan Bali.' },
    { name:'Pak Gunawan', age:60, city:'Balikpapan',      emoji:'💎', avatarBg:'linear-gradient(135deg,#1a2a2a,#2a4a4a)',
      budget:120000000, housing:'prime_house', car:'supercar', vacation:50000000,
      bio:'Konglomerat tambang batu bara, kolektor seni modern dan wiski langka.' },
  ],

  babies: [
    { name:'Sari',   age:22, city:'Jakarta Selatan', emoji:'👸', avatarBg:'linear-gradient(135deg,#2a0a1a,#5a1a3a)',
      availability:'3x/week', education:'S1',  status:'mahasiswi',
      bio:'Anak Fisip UI, suka K-drama dan explore restoran baru.' },
    { name:'Dewi',   age:24, city:'Bandung',         emoji:'🌸', avatarBg:'linear-gradient(135deg,#1a0a2a,#4a1a5a)',
      availability:'1x/week', education:'S1',  status:'wanita_karir',
      bio:'Brand manager di startup fashion, hobi pilates dan yoga.' },
    { name:'Nadia',  age:21, city:'Surabaya',        emoji:'🦋', avatarBg:'linear-gradient(135deg,#0a1a2a,#1a3a5a)',
      availability:'2x/month', education:'SMA', status:'tidak_bekerja',
      bio:'Fresh graduate SMA, prepare S1. Suka baking dan skin care.' },
    { name:'Putri',  age:26, city:'Bali',            emoji:'🌺', avatarBg:'linear-gradient(135deg,#2a1a0a,#5a3a1a)',
      availability:'daily',   education:'S1',  status:'entrepreneur',
      bio:'Online shop owner 200k followers IG, digital creator penuh ide.' },
    { name:'Alya',   age:23, city:'Yogyakarta',      emoji:'🎓', avatarBg:'linear-gradient(135deg,#0a2a0a,#1a5a2a)',
      availability:'1x/month', education:'S2',  status:'mahasiswi',
      bio:'Mahasiswi S2 Ekonomi UGM, riset ekonomi digital dan fintech.' },
    { name:'Rara',   age:25, city:'Jakarta Barat',   emoji:'💅', avatarBg:'linear-gradient(135deg,#2a0a0a,#5a1a1a)',
      availability:'3x/week', education:'D3',  status:'wanita_karir',
      bio:'Beauty consultant brand Korea, freelance MUA di wedding.' },
    { name:'Tika',   age:27, city:'Medan',           emoji:'🌿', avatarBg:'linear-gradient(135deg,#0a2a1a,#1a5a3a)',
      availability:'1x/week', education:'S1',  status:'wanita_karir',
      bio:'Dokter muda di klinik swasta, suka hiking dan lari pagi.' },
    { name:'Cindy',  age:20, city:'Jakarta Timur',   emoji:'✨', avatarBg:'linear-gradient(135deg,#1a1a2a,#3a3a5a)',
      availability:'2x/month', education:'SMA', status:'mahasiswi',
      bio:'Maba FEB Trisakti, aktif di BEM, hobi menyanyi dan dance.' },
    { name:'Mega',   age:28, city:'Makassar',        emoji:'🦩', avatarBg:'linear-gradient(135deg,#2a0a2a,#5a1a5a)',
      availability:'2x/month', education:'S1',  status:'entrepreneur',
      bio:'Founder catering halal, ex-atlet renang, suka masak fusion.' },
    { name:'Wulan',  age:22, city:'Semarang',        emoji:'🌙', avatarBg:'linear-gradient(135deg,#0a0a2a,#1a1a5a)',
      availability:'1x/week', education:'S1',  status:'mahasiswi',
      bio:'Anak Undip Arsitektur, illustrator freelance part-time.' },
    { name:'Fira',   age:24, city:'Tangerang',       emoji:'🎤', avatarBg:'linear-gradient(135deg,#2a1a1a,#5a3a3a)',
      availability:'3x/week', education:'D3',  status:'wanita_karir',
      bio:'Penyiar radio dan host event, 50k followers TikTok.' },
    { name:'Bella',  age:26, city:'Solo',            emoji:'🌹', avatarBg:'linear-gradient(135deg,#1a0a2a,#3a1a5a)',
      availability:'daily',   education:'S1',  status:'entrepreneur',
      bio:'Wedding organizer muda, suka travel dan photography landscape.' },
    { name:'Keisha', age:23, city:'Jakarta Selatan', emoji:'🦄', avatarBg:'linear-gradient(135deg,#1a0a3a,#3a0a5a)',
      availability:'2x/month', education:'S1',  status:'mahasiswi',
      bio:'Anak Binus desain komunikasi visual, aktif lomba desain internasional.' },
    { name:'Salma',  age:25, city:'Surabaya',        emoji:'🌊', avatarBg:'linear-gradient(135deg,#0a1a3a,#0a2a5a)',
      availability:'1x/week', education:'S2',  status:'wanita_karir',
      bio:'Analis keuangan bank BUMN, hobi freediving dan kitesurfing.' },
    { name:'Luna',   age:21, city:'Bali',            emoji:'🌠', avatarBg:'linear-gradient(135deg,#2a0a2a,#4a0a4a)',
      availability:'3x/week', education:'SMA', status:'entrepreneur',
      bio:'Influencer travel 150k followers, jual preset foto dan jasa foto produk.' },
  ],
};
